findfriends/urls.py
from django.urls import path

from . import views

app_name = 'findfriends'

urlpatterns = [
    path('searchfriends/', views.searchfriends, name='searchfriends'),
    path('friendlist/', views.friendlist, name='friendlist'),
    path('friendlist/data/', views.data, name='data'),
]

findterest_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('curhat/', include('curhat.urls')),
    path('findfriends/', include('findfriends.urls')),
    path('contribute/', include('contribute.urls')),
    path('jawab/', include('jawab.urls')),
    path('tanya/', include('tanya.urls')),
    path('', include('register.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
]

findfriends/models.py
from django.db import models

# Create your models here.
TAHUN = [
    ('2020', '2020'),
    ('2019', '2019'),
    ('2018', '2018'),
    ('2017', '2017'),
    ('2016', '2016'),
    ('2015', '2015'),
    ('Alumni', 'Alumni'),
]

class Find(models.Model):
    
    tahun = models.CharField(max_length=20, choices=TAHUN)

    

findfriends/forms.py
from django import forms
from .models import Find
from contribute.models import ContributeModel
from register.models import AdditionalUserModel

class Findform(forms.ModelForm):
    class Meta:
        model = AdditionalUserModel
        fields = ['major', 'university']

        labels = {
            'university' : 'Your friends current / last university', 'major' : 'Your friends current / last major',
        }
        widgets = {
            'university' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'University'}),

            'major' : forms.TextInput(attrs={'class' : 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'Major'}),

        }
class TahunForm(forms.ModelForm):
    class Meta:
        model = Find
        fields = ['tahun']

        labels = {
            'tahun' : 'Year of Entry',
        }

findfriends/views.py
from django.shortcuts import render, redirect
from .forms import Findform, TahunForm
from .models import Find
from contribute.models import ContributeModel
from register.models import AdditionalUserModel
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import JsonResponse
import json
from pip._vendor import requests
from django.core import serializers


# Create your views here.
def searchfriends(request):
    form = Findform()
    formtahun = TahunForm()
    if request.method == "POST":
        form = Findform(request.POST)
        if form.is_valid():
            return redirect('/friendlist/')
    else:
        form = Findform()

    return render(request, 'search.html', {'form' : form, 'formtahun' : formtahun})

def friendlist(request):
    form = Findform(request.POST)
    formtahun = TahunForm(request.POST)
    tahun = formtahun['tahun'].value()
    # univ = form['university'].value()
    jurusan = form['major'].value()
    hasil = AdditionalUserModel.objects.filter(year_of_entry=str(tahun), major=jurusan)
    return render(request, 'list.html', {'form' : form, 'formtahun' : formtahun, 'hasil' : hasil})

def data(request):
    url_destination = request.GET['q']
    jeson = serializers.serialize('json', AdditionalUserModel.objects.filter(university__icontains=url_destination))
    data2 = json.loads(jeson)
    return JsonResponse(data2, safe=False)

findfriends/templates/list.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Friend List</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- <link rel="stylesheet" href="{% static 'findfriend/css/ff.css' %}"> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    .utama, .parent-card{
        margin-top: 60px;
        font-family: Poppins;
    }
    .utama{
        text-align: center;
    }
    :placeholder-shown{
        text-align: center;
    }
    .parent-card{
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }
    ul {
        border: solid 1px #0092FF;
        background-color: #F0F9FE;
        border-radius: 30px;
        margin: 20px 0px;
        width: 500px;
        list-style: none;
    }
    ul .inner {
        padding: 20px;
        overflow: hidden;
        display: none;
    }
     .isi {
        border: solid 1px #0092FF;
        background-color: #F0F9FE;
        border-radius: 30px;
        margin: 20px 0px;
        width: 500px;
        padding: 20px;
        overflow: hidden;
    }
    .inner p{
        font-size: 14px;
    }

    ul li {
        margin: 10px 20px;
        font-weight: bolder;
        font-size: 20px;
    }
    .icon img{
        float: right;
        width: 30px;
        height: 30px;
    }
    .foto{
        float: left;
        width: 40%;
    }
    .profail{
        float: left;
        width: 60%;
    }
    .foto img{
        width: 120px;
        height: 120px;
        border: solid 3px #0092FF;
        border-radius: 50%;
        margin-top: 10px;
    }
    #klik{
        margin-top: 50px;
        text-align: center;
    }
</style>
{% endblock %}

{% block content %}
<section>
    <h1>Hasil Pencarian</h1>
    <p>Semoga ada teman yang sesuai :)</p>
    <div id="klik">
        <button class="button">Change Background</button>
    </div>  
    <div class="parent-card">
        <h2>Cari Universitas (Tapi tidak memfilter field lainnya)</h2>
        <input id="find" placeholder="Nama Universitas"><br>
        <div class="hasil">
            {% for i in hasil %}
            <ul class="accordion">
                <li>
                    <a class="toggle">{{ i.username }}</a>
                    <a class="icon" href=#><img src="https://cdn0.iconfinder.com/data/icons/leading-international-corporate-website-app-collec/16/Expand_menu-512.png"></a>
                    <div class="inner">
                        <div class="row">
                            <div class="foto">
                                <img src="{{ i.image_url }}">
                            </div>
                            <div class="profail">
                                <h3><strong>{{ i.first_name }}</strong></h3>
                                <p id="list"><img src="https://secure.webtoolhub.com/static/resources/icons/set112/6f62880a.png" width="30px" height="30px"> {{ i.interest }}</p>
                                <p id="list"><img src="https://i.pinimg.com/originals/b1/b7/de/b1b7de37299d6d589ba3d7e28652869b.png" width="30px" height="30px"> {{ i.university }}</p>
                                <p id="list"><img src="https://static.thenounproject.com/png/1141593-200.png" width="30px" height="30px"> {{ i.social_media }}</p>
                            </div>
                        </div> 
                    </div>
                </li>
            </ul>
        {% endfor %}
        </div>
    </div>
    
    <script>
        $("#klik").on( "click", ".button", function(event) {
            $("body").css("background-color", " rgb(132, 226, 255)")
        });
    </script>
    <script>
      $('.icon').click(function(e) {
        e.preventDefault();
      
        let $this = $(this);
      
        if ($this.next().hasClass('show')) {
            $this.next().removeClass('show');
            $this.next().slideUp(350);
        } 
        else {
            $this.parent().parent().find('li .inner').removeClass('show');
            $this.parent().parent().find('li .inner').slideUp(300);
            $this.next().toggleClass('show');
            $this.next().slideToggle(300);
        }
      });
    </script>
    <script type="text/javascript">
        $('#find').keyup(function(){
            var isifind = $('#find').val();
            var urlnya = '/findfriends/friendlist/data/?q=' + isifind;
    
            $.ajax({
                url: urlnya, 
                success: function(data){
                    console.log(data);
                    var objresult = $('.hasil');
                    objresult.empty();
    
                    for(i=0; i<data.length; i++){
                        var foto = data[i].fields.image_url;
                        var menarik = data[i].fields.interest;
                        var kampus = data[i].fields.university;
                        var sosmed = data[i].fields.social_media;
                        objresult.append('<div class="isi"><div class="row"><div class="foto"><img src=' + 
                            foto + '></div><div class="profail"><h3><p id="list"><img src="https://secure.webtoolhub.com/static/resources/icons/set112/6f62880a.png" width="30px" height="30px">' + 
                                menarik + '</p><p id="list"><img src="https://i.pinimg.com/originals/b1/b7/de/b1b7de37299d6d589ba3d7e28652869b.png" width="30px" height="30px">' + kampus + '</p><p id="list"><img src="https://static.thenounproject.com/png/1141593-200.png" width="30px" height="30px">' + 
                                    sosmed + '</p></div></div></div>');
                    }
                }
            });
        });
    </script>
</section>


{% endblock %}

findfriends/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Search Friend</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'main/css/lending-page.css' %}">
<link rel="stylesheet" href="{% static 'findfriend/css/ff.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock %}

{% block content %}
<section class="src" style="margin-top: -100px;">
    <div id="judul" class="kiri">
        <h1><label class="biru" for="">Find </label>Friends</h1>
        {% if user.is_authenticated %}
            <h2>Carilah temanmu berdasarkan kategori berikut :</h2>
            <div class="serc">
                <form method="POST" action="{% url 'findfriends:friendlist' %}">
                    {% csrf_token %}
                    
                    <label for="name">{{ formtahun.tahun.label_tag }}</label><br>
                    {{ formtahun.tahun }}
                    <br><br>
                    <label for="name">{{ form.major.label_tag }}</label><br>
                    {{ form.major }}
                    <br><br><br>
                    <button type="submit" value="Save" class="button"><h4>SEARCH</h4></button>
                </form>
            </div>
            {% else %}
                <p style="font-size:18px; font-weight:bold;">Anda perlu log in terlebih dahulu untuk bisa menemukan temanmu. <a href="/login/" style="color: #0092FF;">Log In</a></p>
            {% endif %}
    </div>

    <div class="kanan">
        <img src="{% static 'findfriend/card1.svg' %}" alt="" style="width: 40vmax; height: 40vmax;">
    </div>
</section>


{% endblock %}